apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - redis-service.yaml
  - redis-deployment.yaml
  - app-service.yaml
  - app-loadbalancer.yaml
  - app-deployment.yaml
  - network-policies.yaml
